# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b018ab0cb7502eb3ccdae34d9daa73cb5549a87f431a5006198637ade60030514cb13b4bb75a764e673be2d3423fc8a50f1138bc83151c3e7db5f8396f85f6c0

test:
  secret_key_base: 38a1442b3a2979f5fc944fdc908636ac848ecc019a82e0c2ea3fbfba5d0a9687ed45f1f123789c53d138e795640095b810075b05e4b4427acc9e10041422e165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
